
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppLayout } from '@/components/layout/app-layout';
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from '@/context/AuthContext';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Memoria',
  description: 'Personal Idea Tracker and Family Diary',
  manifest: '/manifest.json', // This is the most crucial link for PWA
  formatDetection: {
    telephone: false, // Good for mobile UX
  },
  themeColor: [ // Provides theme colors for light and dark modes
    { media: '(prefers-color-scheme: light)', color: '#B0E2FF' }, // Your primary light theme color
    { media: '(prefers-color-scheme: dark)', color: '#18181b' },  // A generic dark theme color (Tailwind zinc-900)
  ],
  icons: {
    icon: [ // General purpose icons, can be used for favicon etc.
      { url: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png' },
    ],
    shortcut: ['/icons/icon-96x96.png'], // For browser shortcuts or bookmarks
    apple: [ // For Apple 'Add to Home Screen' and touch icons
      { url: '/icons/icon-152x152.png', sizes: '152x152', type: 'image/png' },
      { url: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png' },
    ],
    // You can add more specific icon types here if needed, like 'other' for favicons
    // other: [
    //   { rel: 'icon', url: '/favicon.ico' }, // If you had a favicon.ico
    // ],
  },
  appleWebApp: {
    capable: true, // Indicates the web app is designed for a native-like experience
    title: "Memoria", // The name that appears under the icon on the iOS home screen
    statusBarStyle: 'default', // Options: 'default', 'black', 'black-translucent'
    // startupImage: [ // Optional: Define splash screens for different iOS device sizes
    //   // Example (you would need to create these image files):
    //   // {
    //   //   url: '/icons/apple-splash-2048x2732.png', 
    //   //   media: '(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)',
    //   // },
    // ],
  },
  // Viewport is usually handled by Next.js but explicit definition doesn't hurt.
  // viewport: 'width=device-width, initial-scale=1, viewport-fit=cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* The <head> tag and its contents (like manifest, theme-color, icons)
          will be automatically generated by Next.js based on the metadata object above.
          No need to manually write <head> here. */}
      <body className={`${inter.variable} antialiased`} suppressHydrationWarning>
        <AuthProvider>
          <AppLayout>
            {children}
          </AppLayout>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
